# Generated by Django 3.2.6 on 2021-08-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('mob', models.CharField(default='', max_length=50)),
                ('usern', models.CharField(default='', max_length=50)),
                ('pw', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
